### ISSUE TITLE
Forgot to upload macOS dmg for v2.0 release?

### ISSUE THREAD

**Issue by MDX-Tom** [straight-tamago/misakaX#103]
There is only Windows version for v2.0.

**Comment by TianzhuQin** [comment]
Expect 2.0 for Mac!

**Comment by fanbie61100** [comment]
> It was uploaded, i have version 2.0 for mac. I don't know what happened but maybe some bug that was found last min? I wont upload it here for now as I don't want spread something that could brick your devices. Btw I tested it and AOD works on 18 RC, other tweaks idk, didn't test them.
> 
> EDIT: I also tested Stage Manager on 18 RC on my iPad mini 5 gen. and it works. ![image](https://private-user-images.githubusercontent.com/98495831/365948301-6841f85a-6324-4278-841b-316d1d8437ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTk4NTksIm5iZiI6MTcyNTk1OTU1OSwicGF0aCI6Ii85ODQ5NTgzMS8zNjU5NDgzMDEtNjg0MWY4NWEtNjMyNC00Mjc4LTg0MWItMzE2ZDFkODQzN2VjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA5MTIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlYmFjOGMxYmRjOTk0ZDYzM2E3MGQwNzMyODBjNGE1ZGJlMzgzNzU0ZDNjMDZiNzQzMDhjOWE3OTQ5MzhjODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kcO1qkgVJF_nXDKK6nVXPCj8OtJW6C4kLiMn8J2d4Bs) ![image](https://private-user-images.githubusercontent.com/98495831/365948669-ce593024-d622-4503-8daa-d77c441fe6bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTk4NTksIm5iZiI6MTcyNTk1OTU1OSwicGF0aCI6Ii85ODQ5NTgzMS8zNjU5NDg2NjktY2U1OTMwMjQtZDYyMi00NTAzLThkYWEtZDc3YzQ0MWZlNmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA5MTIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMGI5M2M4MzlhMWVmMWMzZTY0ZjJlYTQyNWYwYjA3YzY0MDZlODE2OTRkMjA0ZTNmYzZmNTllNTkyOGRkN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OpwmZCloESc7bjd37_TpS19RmPblCyWes3X749vrCrI)

When is the estimated time to fix and upload the Mac version

**Comment by bajader** [comment]
> When is the estimated time to fix and upload the Mac version
I am not the developer

**Comment by fanbie61100** [comment]
> > When is the estimated time to fix and upload the Mac version
> 
> I am not the developer

Can you send me the software package？
