### ISSUE TITLE
IPhone 15 and AoD, Tap to wake don't work anymore

### ISSUE THREAD

**Issue by andreadistefano0512** [straight-tamago/misakaX#109]
In my iPhone 15 if AoD is on tap to wake don't work
after reboot the iphone will reset the .plist file
in settings there's no more AoD setting for change preferences.
(sorry for my bad english)

**Comment by Ayasanorin** [comment]
Similarly, the iPhone 15 is unable to use tap-to-wake functionality when AoD is enabled.
In contrast, the iPhone 12 mini, iPhone 13 Pro, and even the iPad Air 4 (Yes, iPad with AoD warawara) function correctly.
