### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by thsdzmn** [straight-tamago/misakaX#11]
![스크린샷 2024-09-05 오전 5 43 34](https://github.com/user-attachments/assets/acebb014-c12b-4434-a5f6-6557445673db)
I tried everything I could, but in the end this tool didn't work..
Pressing execute did not reboot the device and rebooting manually did not take effect.. plz help
(macOS 11.2 / iPadOS 18.1 b3)

**Comment by Janandrew2009** [comment]
make sure that you trust your computer on your ipad and try to switch your charging cable

**Comment by thsdkr** [comment]
I think my Mac is the problem, so I succeeded with the Windows version👍

**Comment by thsdzmn** [comment]
I think my Mac is the problem, so I succeeded with the Windows version👍
