### ISSUE TITLE
Animation Clock UI break standby mode

### ISSUE THREAD

**Issue by Mowd** [straight-tamago/misakaX#113]
Once you enable Animation Clock UI, the standby mode will break into two parts and unable to undo, even uncheck the Animation Clock UI. 

![IMG_4441](https://github.com/user-attachments/assets/a4dea463-201c-4a8a-82e1-f8c24cbbaaf7)
![IMG_4442](https://github.com/user-attachments/assets/bb8547f1-1ec0-43a3-a709-084b0b81b4ae)

**Comment by Janandrew2009** [comment]
Untill is it fixed you can use nugget and enable lthe new lock screen ui while disabling the duplicate button
<img width="1112" alt="Screenshot 2024-09-10 at 11 41 11 PM" src="https://github.com/user-attachments/assets/e9648355-7c37-46b4-ac41-68d40ce96421">

**Comment by themaik882** [comment]
or when without enable just still bug 
well

**Comment by themaik882** [comment]
but you cant 
you life iPhone

**Comment by Mowd** [comment]
By using nugget v2.2 and unchecking all feature flag, fix the problem!!
Many thanks.

**Comment by 34306** [comment]
Will fix on next release!

**Comment by themaik882** [comment]
![image](https://github.com/user-attachments/assets/f63191fa-c17a-411c-8c37-a973e5206539)

i idea 💡 Understood

**Comment by June0105** [comment]
> ![image](https://private-user-images.githubusercontent.com/48050582/367582389-f63191fa-c17a-411c-8c37-a973e5206539.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NzUzOTEsIm5iZiI6MTcyNjY3NTA5MSwicGF0aCI6Ii80ODA1MDU4Mi8zNjc1ODIzODktZjYzMTkxZmEtYzE3YS00MTFjLThjMzctYTk3M2U1MjA2NTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDE1NTgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZjQ5NGZhNTc4YWJiNjEyYmY5MjkyZmY1MzVhOGE2ZmIxODIxNmYxN2QzNzRiOTgzOTI3YjkxMTI3OWFjMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NMff11E-S-NJtjhx5Ezsdpfv9YeybgccvLr_IxdAOpE)
> 
> i idea 💡 Understood

I didn't understand what you were saying
Can you explain it again?
