### ISSUE TITLE
iOS 18.0 RC Problems

### ISSUE THREAD

**Issue by Janandrew2009** [straight-tamago/misakaX#116]
1- Always on Display can't be triggered using the shourtcuts app (The action "Set Always on Display" is not supported on iPhone)

2- Always on Display section completely disappears from the settings app, after being visible after the Misaka X reboot, after few minutes

3- All the tweaks of Misaka X are reverted to original after a device reboot

iPhone 11 Pro Max / iOS 18.0 RC / Misaka X V2.1

**Comment by 34306** [comment]
Remove AoD Vibrancy
