### ISSUE TITLE
Error copying file: You can’t save the file “com.apple.MobileGestalt.plist” because the volume “Macintosh HD” is read only.

### ISSUE THREAD

**Issue by danielv05** [straight-tamago/misakaX#12]
Idk why this is happening, but I can't save the mobilegestalt file. I even saved it to my usb drive (which has write permission), but I still can't to anything. Can anyone help? Would be much appreciated

**Comment by DIS-IS-CRAZY** [comment]
I ran it as root to get past that error.

**Comment by danielv05** [comment]
> I ran it as root to get past that error.

How do I do that? I’m new to macOS

**Comment by Apple4787Microbitter** [comment]
> > I ran it as root to get past that error.
> 
> How do I do that? I’m new to macOS

You can do that Via https://support.apple.com/en-us/102367

**Comment by danielv05** [comment]
> > > I ran it as root to get past that error.
> > 
> > 
> > How do I do that? I’m new to macOS
> 
> You can do that Via https://support.apple.com/en-us/102367

Aight, thanks a lot!

**Comment by hirakujira** [comment]
Put the app to your "Downloads" folder and use terminal:
`sudo ~/Downloads/misakaX.app/Contents/MacOS/misakaX`

**Comment by Cirostrazzy** [comment]
it requires me a password

**Comment by Janandrew2009** [comment]
move the app to the applications folder

**Comment by thedonalddon** [comment]
Move misakaX.app to /Applications and run it again.

**Comment by 34306** [comment]
fixed
