### ISSUE TITLE
Redbar "radar" issue on iPhone 12 mini

### ISSUE THREAD

**Issue by vvrgxx** [straight-tamago/misakaX#138]
How to fix Redbar "rdar" issue on the top of screen??

**Comment by vvrgxx** [comment]
![Uploading Lihat foto terbaru.jpeg…]()

**Comment by vvrgxx** [comment]
![Lihat foto terbaru](https://github.com/user-attachments/assets/aacd21eb-b712-4edc-8eba-8ce73614aa3c)

**Comment by Apple4787Microbitter** [comment]
download this and apply it through cowabunga lite https://www.mediafire.com/file/9ynbcy5aie43yq6/rdar_fix.cowperation/file

**Comment by vvrgxx** [comment]
then which one should I choose? "Dynamic Island 2796" or "Dynamic Island 2556"?

**Comment by Apple4787Microbitter** [comment]
> then which one should I choose? "Dynamic Island 2796" or "Dynamic Island 2556"?

Try both. Also, are you using iOS 18 RC or Beta?

**Comment by vvrgxx** [comment]
No i used 17.6.1. After I tried it I can't use "Dynamic Island 2556" but I can use "Dynamic Island 2796" but it's very big for iPhone 12 mini

**Comment by Apple4787Microbitter** [comment]
> No i used 17.6.1. After I tried it I can't use "Dynamic Island 2556" but I can use "Dynamic Island 2796" but it's very big for iPhone 12 mini

Update to 18 RC via: Settings, General, Software Updates, there under automatic updates will be a sign: Beta Updates, choose iOS 18 Public Beta and download the RC version.

**Comment by vvrgxx** [comment]
I'm still waiting for official iOS 18 from Apple. Can this tweak be used on the official iOS 18 which will be released on September 16 2024 too?

**Comment by Apple4787Microbitter** [comment]
> I'm still waiting for official iOS 18 from Apple. Can this tweak be used on the official iOS 18 which will be released on September 16 2024 too?

I think yeah. But you should update to RC, because it is stable enough.

**Comment by vvrgxx** [comment]
![Tangkapan Layar 2024-09-13 pada 14 36 19](https://github.com/user-attachments/assets/fe52b048-42c8-4200-b0f5-78279f051f82)

For now I have successfully used "Dynamic Island 2796" with iOS 17.6.1 after running the RDAR Fix tweak on the iPhone 12 mini. but there is still the same "redbar rdar" when using "Dynamic Island 2556". I will try again when iOS 18 is officially released or wait for the next update from MisakaX. Thank You

**Comment by Apple4787Microbitter** [comment]
> ![Tangkapan Layar 2024-09-13 pada 14 36 19](https://private-user-images.githubusercontent.com/164723211/367193362-fe52b048-42c8-4200-b0f5-78279f051f82.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTM0MjYsIm5iZiI6MTcyNjIxMzEyNiwicGF0aCI6Ii8xNjQ3MjMyMTEvMzY3MTkzMzYyLWZlNTJiMDQ4LTQyYzgtNDIwMC1iMGY1LTc4Mjc5ZjA1MWY4Mi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDczODQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTllY2Q5NjJhNTlmZWI5ODYwZTk3YzcyMmJmZTE1N2FhMGE3NTg2Mzk1NWUwYWRlOTNjOGZiMmNjNGQ5MzBmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qd1fp5UH1pUpvqKHdskqx1I3B2chfApMyocQyofYa_o)
> 
> For now I have successfully used "Dynamic Island 2796" with iOS 17.6.1 after running the RDAR Fix tweak on the iPhone 12 mini. but there is still the same "redbar rdar" when using "Dynamic Island 2556". I will try again when iOS 18 is officially released or wait for the next update from MisakaX. Thank You

Okay. Feel free to close the Issue.

**Comment by samwzlim** [comment]
> download this and apply it through cowabunga lite https://www.mediafire.com/file/9ynbcy5aie43yq6/rdar_fix.cowperation/file

Do you have this file for iPhone 13 Mini? I applied it for mine, but the resolution seems a little off.
