### ISSUE TITLE
Unable to use it on Mac with Intel CPU

### ISSUE THREAD

**Issue by SharKing09** [straight-tamago/misakaX#148]
Hi, I have a macbook air with an Intel chip and every time it tells me that there is a problem with the shared folders of python. If you can help me I would appreciate it very much. I tried on a mac with an m1 chip and everything goes smoothly without problems

**Comment by augustobob** [comment]
Same issue here. MacOS 12.7.5 intel. 
<img width="1034" alt="Print 2024-09-16 às 00 26 49" src="https://github.com/user-attachments/assets/64849b8f-5acf-4f6f-950d-9bf29bb2a352">

**Comment by SharKing09** [comment]
yes is the same issue

**Comment by SharKing09** [comment]
yes @augustobob is the same issue

**Comment by hanglics** [comment]
Is this with Misaka 2.2 or earlier versions?

**Comment by SharKing09** [comment]
@hanglics i have this issue with every misakaX versions.

**Comment by hanglics** [comment]
I had this issue with v1.8, haven't tried since, let me have a go with v2.2

**Comment by SharKing09** [comment]
@hanglics i have this issue with 2.2 too but idk if is a issue with only my mac but i downloaded all the things that i had to download and it doesn't work. even on older versions where the is the button to download py3

**Comment by hanglics** [comment]
I just tried v2.2, it worked for me. So it might be some issues with your python installation. I'm using a MacBook Pro 16 inch with intel core from 2019. And I have python 3.7 installed as default with the path in the environment path.

**Comment by SharKing09** [comment]
@hanglics ok i try to reintall it and hopefully it works but i don't think the application the problem

**Comment by TheMightyBattleCat** [comment]
Getting the same issue on the latest build 2.2. 
Intel Mac - macOS Montery 12.7.5

**Comment by augustobob** [comment]
I have not tested the latest version on my Mac again since I downloaded misakax in a spare windows machine I have around, I can try later and update here if it works

**Comment by SCADDIVER** [comment]
Has anyone found a solution to this problem ? What else needs to be done to Python App after installation ?

**Comment by SharKing09** [comment]
> Has anyone found a solution to this problem ? What else needs to be done to Python App after installation ?

for now no

**Comment by mrcarman7** [comment]
Same with TheMightyBattleCat, I'm on 12.76 and I don't have that file
