### ISSUE TITLE
EUバージョンの適用が可能かどうかについてのお問い合わせ

### ISSUE THREAD

**Issue by cats-love** [straight-tamago/misakaX#15]
こんにちは、このアプリを利用してEUバージョンのモデル名でもiPhoneを変えることはできますか？
もしそうなら、Epic game storeのような他社のアプリをインストールして、フォールガイズやフォートナイトのようなゲームができるようになるかもしれません。
考慮していただけますか？

**Comment by 34306** [comment]
私のコンピュータでそれを試してみました。日本にいる友人も試しましたが、すべてうまくいきませんでした。私はベトナムでは VI/VN を試し、友人は日本では J/JA/JP を試しました。
