### ISSUE TITLE
Boot Chime option has no effect?

### ISSUE THREAD

**Issue by i0ntempest** [straight-tamago/misakaX#154]
I have a 15 Pro, boot chime option does not seem to do anything. Is it supposed to make your device make a chime while booting like a Mac?

**Comment by n1ckplays** [comment]
same

**Comment by VoltIcaRus** [comment]
@i0ntempest  Come on this tool just enables the option. 
You have to go into your settings and enable it yourself. 
And since you're already using an iPhone 14 or later, the toggle menu is already enabled. 
so it's completely irrelevant 
You can enable this option for iPhones 13 and below

**Comment by i0ntempest** [comment]
@VoltIcaRus Thanks, I've no idea this is a built in accessibility function lol. I thought it's like on macOS you need to mess with NVRAM to enable/disable boot sound.
