### ISSUE TITLE
Rdar error

### ISSUE THREAD

**Issue by HELLSNAKES** [straight-tamago/misakaX#16]
I tried on iPhone 11 iOS 17.6.1(21g101) and encountered this error:
![image](https://github.com/user-attachments/assets/7963da69-e45c-469d-817b-2e21fdd1b480)

**Comment by moduledd** [comment]
iirc visibleisland has this issue too, but its fixed by changing the res.

**Comment by moduledd** [comment]
ur SOL basically

**Comment by Janandrew2009** [comment]
> iirc visibleisland has this issue too, but its fixed by changing the res.

Does Visible island work on ios 18?

**Comment by 34306** [comment]
Stock bug. Can't fix at this moment!
