### ISSUE TITLE
Does selecting the "Apple Pencil" option allow for the use of it on an iPhone?

### ISSUE THREAD

**Issue by WiseJar** [straight-tamago/misakaX#163]
I have an Apple Pencil, would it work on my iPhone using this tool?

**Comment by singhalrishi27** [comment]
Same question

**Comment by Galafador** [comment]
what does it do then?

**Comment by himubey** [comment]
Why does this feature exist in this app?

**Comment by JackuXL** [comment]
Same question

**Comment by TomerGamerTV** [comment]
why did he close if the question wasn't answered...

**Comment by aarhonn** [comment]
The gummint forced him to

> why did he close if the question wasn't answered...
