### ISSUE TITLE
Dynamic Island disappears when not in use

### ISSUE THREAD

**Issue by Svetrikk** [straight-tamago/misakaX#164]
When not using Dynamic Island, it disappears when not using it.

**Comment by A350-900** [comment]
That's how dynamic island works. It's Apple's program design, just like when you screenshot on a device with dynamic island, the island won't appear when no app is occupying it either.

**Comment by Svetrikk** [comment]
> That's how dynamic island works. It's Apple's program design, just like when you screenshot on a device with dynamic island, the island won't appear when no app is occupying it either.

Yes but when it is not shown and tap there, it shows for a second and then disappears. Or is it behaving as normal?

**Comment by A350-900** [comment]
> > That's how dynamic island works. It's Apple's program design, just like when you screenshot on a device with dynamic island, the island won't appear when no app is occupying it either.
> 
> Yes but when it is not shown and tap there, it shows for a second and then disappears. Or is it behaving as normal?

It is, just like how it works on a device with dynamic island.

**Comment by YouYuu1** [comment]
On iOS 17.5.1 and 17.6.1, Dynamic Island display all the time, only on iOS 18 disappears

**Comment by Svetrikk** [comment]
> On iOS 17.5.1 and 17.6.1, Dynamic Island display all the time, only on iOS 18 disappears 

Oh that's how I remember when I was using cowabunga. I thought this is a bug
