### ISSUE TITLE
Standby mode

### ISSUE THREAD

**Issue by Janandrew2009** [straight-tamago/misakaX#17]
Standby mode doesn’t fully work when enabling AOD & Dynamic island - iPhone 11 Pro Max / iOS 18.0 Beta 8

**Comment by 34306** [comment]
Hardware issue.

**Comment by Janandrew2009** [comment]
How is it a hardware issue it used to work before using misaka x
My problem with standby display is that it displays a black screen when it is enabled

**Comment by 34306** [comment]
Just disable the AoD :/
Your device is not suppose to use that then don't try. Some how they limit it to later models maybe for that reason

**Comment by Janandrew2009** [comment]
Ok thanks, I will try and update you ASAP
