### ISSUE TITLE
Does the functions support the new IOS 18 (not beta)

### ISSUE THREAD

**Issue by AhRickkyyyyyy** [straight-tamago/misakaX#177]
I am currently using iPhone 13 Pro Max on IOS 17.3.1 and I was applying the charge limit. I was wondering that is now Misaka X supports devices on IOS 18 (not beta) now as I also wanted to apply AOD on my phone.

**Comment by shoxrux2006** [comment]
> I am currently using iPhone 13 Pro Max on IOS 17.3.1 and I was applying the charge limit. I was wondering that is now Misaka X supports devices on IOS 18 (not beta) now as I also wanted to apply AOD on my phone.

yeah
