### ISSUE TITLE
Could someone explain Internal Storage and Boot Chime for me? Thanks in advance!

### ISSUE THREAD

**Issue by DannyH3103** [straight-tamago/misakaX#184]

**Comment by aaronjrodrigues** [comment]
Not sure about internal storage but for the boot chime there was an accessibility setting introduced in the iPhone 14 and later that included a boot chime so this basically enables that for other devices

**Comment by DannyH3103** [comment]
Thank you!

**Comment by DannyH3103** [comment]
I found out that internal storage lets you see system files in >General>iPhone Storage>System Data
