### ISSUE TITLE
i used the latest misakaX 2.2, my chinese model iphone 5 pro(ios 18.1 beta4) apple intelligence can't appear on the phone.

### ISSUE THREAD

**Issue by lyly8306** [straight-tamago/misakaX#192]
rt, i tried serval times but nothing happens on my iphone?

**Comment by jf02134915** [comment]
r u using windows or macOS?

**Comment by lyly8306** [comment]
> r u using windows or macOS?

windows 11, thx for asking.

**Comment by jf02134915** [comment]
> > r u using windows or macOS?
> 
> windows 11, thx for asking.

Gotcha im gonna try that on Windows 11
see if it will be the same or not

Thx for ur reply

**Comment by jf02134915** [comment]
![image](https://github.com/user-attachments/assets/49455dd9-c39f-4b00-b859-8922cc83b584)
well i got this...any solutions？

**Comment by Ma-27** [comment]
> 

exactly the same problem. I am using windows 10.

**Comment by qianyueping1211** [comment]
安装最新的Python，添加到环境变量，选择自定义安装，选择安装pip；
 管理员模式打开命令行，使用 pip install Pymobiledevice3，之后这个错误会消失。
