### ISSUE TITLE
Error while opening MisakaX 2.2 on windows 10

### ISSUE THREAD

**Issue by Ma-27** [straight-tamago/misakaX#193]
System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   在 System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   在 System.Diagnostics.Process.Start()
   在 iPhone.ExecuteProcess(String fileName, String arguments, String workingDir)
   在 iPhone.GetPymobiledevice3Version()
   在 misakaX.MainWindow.<<-ctor>b__11_1>d.MoveNext()

Using windows 10, device is ipad air(M2), ios 18.0 release.

**Comment by achilles0x** [comment]
I think this will help you.httpsI put the necessary dlls in the archive

**Comment by achilles0x** [comment]
install this//mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWwIf you don't have the c compliator, install it.(gcc or clang)

**Comment by Ma-27** [comment]
Thank you. I have the MinGW for Clion but I do not know how to configure it with misakaX. is there methods to use  MinGW?

**Comment by moooonje** [comment]
Use 'pip install Pymobiledevice3'

**Comment by Ma-27** [comment]
Yes, it works. Thank you very much!

**Comment by chenlei9891** [comment]
> Yes, it works. Thank you very much!



> Yes, it works. Thank you very much!


hi, its means reseat the time？thinks

**Comment by chenlei9891** [comment]
> Use 'pip install Pymobiledevice3'

how to use ？thinks

**Comment by chenlei9891** [comment]
楼主好，看你是国人。请教下我也是这个问题，最后您是怎么解决的呢 。看上面回复在git上下载了Pymobiledevice3后怎么操作呢？是打开特定的md文件嘛？打扰了，冒昧期待回复，谢谢。thinks

**Comment by Ma-27** [comment]
不是，用pip命令行安装Pymobiledevice3这个包就可以了，不需要打开特定的md文件。如果你的电脑没有python环境和pip包管理器那需要你自己安装这些
