### ISSUE TITLE
it’s support ios 16.7.4??

### ISSUE THREAD

**Issue by WawanGanz** [straight-tamago/misakaX#20]
i just want dynamic island

**Comment by kussaqqqehateyou** [comment]
yeah, you can use that tool to enable Dynamic Island on your iOS.

**Comment by 34306** [comment]
It should be, but use at your own risk!

**Comment by 34306** [comment]
> > yeah, you can use that tool to enable Dynamic Island on your iOS.
> 
> bro i just try but don’t work, my iphone just restarted

Then it win't work. The app is designed for iOS 17.0+

**Comment by WawanGanz** [comment]
> > > yeah, you can use that tool to enable Dynamic Island on your iOS.
> > 
> > 
> > bro i just try but don’t work, my iphone just restarted
> 
> Then it win't work. The app is designed for iOS 17.0+

when yahhhhh…  wait for support ios 16

**Comment by kussaqqqehateyou** [comment]
> Confirm that Dynamic Island is available on ios16. Has anyone tried to turn on AOD on ios16?

AOD causes bootloop on iOS 17 and lower
