### ISSUE TITLE
Do I have to do this again and again after rebooting/ restarting my iPhone 13

### ISSUE THREAD

**Issue by mujtaba454** [straight-tamago/misakaX#203]
Do I have to keep doing this procedure again and again after restarting the phone?
Because I tried to restart my phone by pressing volume up down and power button, when the device turned on this features were gone.

Also, I am unable to get Apple Intelligence to download it is stuck on connect to Wi-Fi to download when I say, hey Siri!

**Comment by by6et** [comment]
Possibly not .  it still remains there on my 13mini after reboot.   regarding of the Charge limit and Dynamic island.

**Comment by mujtaba454** [comment]
Thanks
