### ISSUE TITLE
Unable to check Software Update after tweaking

### ISSUE THREAD

**Issue by CyanideB0y** [straight-tamago/misakaX#215]
Currently on ios18. Used misaka for few tweaks. Now got an error with software update.
![IMG_1296](https://github.com/user-attachments/assets/dcb78181-030c-47af-a131-adc152588393)

**Comment by brady9870** [comment]
Don’t click the internal storage function

**Comment by CyanideB0y** [comment]
> Don’t click the internal storage function 

How do i reverse it now?

**Comment by CyanideB0y** [comment]
I think i fixed it! Cheers man!
