### ISSUE TITLE
misakaX 2.2 版本  IOS18.1（22B5045g），重启后没有出现重置手机及AI提醒。

### ISSUE THREAD

**Issue by qianyueping1211** [straight-tamago/misakaX#225]
手机已经使用外区ID，并且设置了美国地区+英文，使用 
pip install Pymobiledevice3，正常安装后，重启时没有出现预期的效果，而是直接进入了手机系统。

![image](https://github.com/user-attachments/assets/6efd6f2f-ec67-4ad5-ad8f-1f086f4b50f3)

**Comment by KeJHweb** [comment]
好像同时要把Disable Shutter Sound勾选上

**Comment by freeAbrams** [comment]
勾选Disable Shutter Sound以修改型号为LL/A从而绕过针对CH/A型号Apple Intelligence的限制。
使用期间不要尝试使用爱思等工具，将导致绑定序列号的验机数据被污染

**Comment by qianyueping1211** [comment]
我重新更新了问题，我已经勾选了 Disable Shutter Sound，问题还是这样。

**Comment by rien7** [comment]
用1.5版本

**Comment by qianyueping1211** [comment]
感谢提醒使用1.5版本，但是还是没有达到预期。情况如下：
 我使用美区ID登录，misakaX 1.5版本（两次分别勾选了AI + stutter Sound，及只选择AI），在重启后地区出现了重置手机提升，但是最终型号还是CH/A，并且没有出现AI的试用功能。
 并且我看 misakaX 1.5版本 最大是支撑IOS 18.1beta 3，我现在是IOS18.4 beta4 public beta。

**Comment by rien7** [comment]
>  我使用美区ID登录，misakaX 1.5版本（两次分别勾选了AI + stutter Sound，及只选择AI），在重启后地区出现了重置手机提升，但是最终型号还是CH/A，并且没有出现AI的试用功能。

地区选美国，语言选英语，Siri语言也选英语

>  并且我看 misakaX 1.5版本 最大是支撑IOS 18.1beta 3，我现在是IOS18.4 beta4 public beta。

测试过 1.5 版本支持 iOS18.1 beta4

**Comment by qianyueping1211** [comment]
今天使用1.5版本的信息如下：
正常重启手机，进入恢复系统，但是输入美区后，并没有出现AI。
![9e60b344a3e621c4eafab9360b0e08b](https://github.com/user-attachments/assets/c80fd826-a688-40b6-8638-7643d4b4fb84)
![9e60b344a3e621c4eafab9360b0e08b](https://github.com/user-attachments/assets/d06fbb9c-c178-4979-b575-7d6c60753ded)
![9e60b344a3e621c4eafab9360b0e08b](https://github.com/user-attachments/assets/58a8dcb4-1b1a-476e-b07a-e354e3ee3448)

**Comment by aliladyman** [comment]
后面解决了吗？我也遇到同样的问题，求指导

**Comment by qianyueping1211** [comment]
没有，我现在已经彻底无法解决了，因为升级了系统。哈哈

**Comment by aliladyman** [comment]
不是可以降级的吗发自我的 iPhone在 2024年9月27日，16:26，Yueping ***@***.***> 写道：﻿
没有，我现在已经彻底无法解决了，因为升级了系统。哈哈

**Comment by dfldylan** [comment]
感谢，点了disable shutter sound就出现apple intelligent的设置了。甚至apple id还是国区的，但是itues商店是美区id。也没让重新激活
