### ISSUE TITLE
Misaka Doesnt let me choose Gestalt file.

### ISSUE THREAD

**Issue by Apple4787Microbitter** [straight-tamago/misakaX#24]
When i click to choose gestalt file and i choose it it says: Error copying file: You can’t save the file “com.apple.MobileGestalt.plist” because the volume “Macintosh HD” is read only.

**Comment by nocontent06** [comment]
Temporary Workaround is:

Open Terminal
Enter sudo and drag and drop the misakaX App out of the misaka app /Contents/MacOS/... into the Terminal
Press enter and enter your Password
The app should start

**Comment by Janandrew2009** [comment]
Move misaka x to the applications folder

**Comment by Apple4787Microbitter** [comment]
> Temporary Workaround is:
> 
> Open Terminal Enter sudo and drag and drop the misakaX App out of the misaka app /Contents/MacOS/... into the Terminal Press enter and enter your Password The app should start

i think it worked

**Comment by Apple4787Microbitter** [comment]
i have another issue, it says RDAR on the top of the phone how do i fix
