### ISSUE TITLE
iOS 18.0 charge limit doesn't work on iPhone 13 mini

### ISSUE THREAD

**Issue by MadeByPP** [straight-tamago/misakaX#246]
I've gone through all the steps and have the actual menu, but even though I set the charging limit to 80%, it's all charged.

**Comment by Kucchan67346** [comment]
Charging limit worked fine on my iPhone 13 mini (iOS 18.1 beta 4).

**Comment by MadeByPP** [comment]
I also set the camera to silent. Unlike the charging limit, it worked properly. I don't know what the problem is.

**Comment by OxYu** [comment]
iOS 18.0 charge limit doesn't work onipad air3

**Comment by vFxMz** [comment]
Same issue on my iPhone 13 Pro, charge limit appear with all the functions but it doesnt work.

**Comment by by6et** [comment]
It works for my 13mini with ios17.3

**Comment by xingbadata** [comment]
> Same issue on my iPhone 13 Pro, charge limit appear with all the functions but it doesnt work. IOS18.0

How did you ultimately resolve the issue?

**Comment by vFxMz** [comment]
> > Same issue on my iPhone 13 Pro, charge limit appear with all the functions but it doesnt work. IOS18.0
> 
> How did you ultimately resolve the issue?

Still haven't figured it out.

**Comment by lslqtz** [comment]
worked on my iphone 12 mini (ios 18.1 beta 3)
but not work (ios 18.1 beta 4)

**Comment by MadeByPP** [comment]
![image](https://github.com/user-attachments/assets/a25a568f-acfe-43be-807a-f93956bf9858)
I thought this might be the cause of the problem. But, I can‘t be sure.

**Comment by MadeByPP** [comment]
> ![image](https://github.com/user-attachments/assets/a25a568f-acfe-43be-807a-f93956bf9858)
> I thought this might be the cause of the problem. But, I can‘t be sure.

This was the cause. I visited an Apple authorized service center and replaced the battery with a new one, and this problem was solved. I hope it will be helpful to those who are experiencing the same problem.
