### ISSUE TITLE
Windows MisakaX Error

### ISSUE THREAD

**Issue by Apple4787Microbitter** [straight-tamago/misakaX#25]
MisakaX windows version says an error: KeyError: DeviceList

**Comment by Apple4787Microbitter** [comment]
also this is showing too: 
![IMG_0241](https://github.com/user-attachments/assets/f5068526-5bf3-422c-b239-e7d077657782)

**Comment by 34306** [comment]
Did you use that on Windows 8 or lower?

**Comment by 34306** [comment]
Fixed in 1.6
