### ISSUE TITLE
rdar text on top

### ISSUE THREAD

**Issue by Apple4787Microbitter** [straight-tamago/misakaX#27]
it says: rdar: numbers
HOW TO FIX

**Comment by Janandrew2009** [comment]
Try v1.4 reset option then re-enable the dynamic island

**Comment by 34306** [comment]
It's a stock bug so yeah, I can't do anything for your iPhone Xr/11

**Comment by Apple4787Microbitter** [comment]
Thanks.

**Comment by SleepyMoz** [comment]
Same issue. Will it ever be fixed?
