### ISSUE TITLE
MisakaX keeps on crashing

### ISSUE THREAD

**Issue by KidKRAK** [straight-tamago/misakaX#295]
so ive done everything i dumped the file i downloaded the misakax app on my pc and itunes not on the microsoft store and also python but when i click apply on the app it loads for like 3 seconds then crash

**Comment by KidKRAK** [comment]
> > so ive done everything i dumped the file i downloaded the misakax app on my pc and itunes not on the microsoft store and also python but when i click apply on the app it loads for like 3 seconds then crash
> 
> Whats the pc youre using?

Windows

**Comment by KidKRAK** [comment]
> > > > so ive done everything i dumped the file i downloaded the misakax app on my pc and itunes not on the microsoft store and also python but when i click apply on the app it loads for like 3 seconds then crash
> > > 
> > > 
> > > Whats the pc youre using?
> > 
> > 
> > Windows
> 
> where did you get the misakaX file from?

I just got it from this GitHub

**Comment by simioni21** [comment]
> > > > > so ive done everything i dumped the file i downloaded the misakax app on my pc and itunes not on the microsoft store and also python but when i click apply on the app it loads for like 3 seconds then crash
> 
> > > > 
> 
> > > > 
> 
> > > > Whats the pc youre using?
> 
> > > 
> 
> > > 
> 
> > > Windows
> 
> > 
> 
> > where did you get the misakaX file from?
> 
> 
> 
> I just got it from this GitHub 

try downloading from this link:

https://onejailbreak.com/blog/misakax/

(if you question the safety of this link you can check the readme file in github for misakaX, they suggest this link)
