### ISSUE TITLE
iP 15 Pro Max - iOS 18.1 beta 3

### ISSUE THREAD

**Issue by iTer99** [straight-tamago/misakaX#30]
I used thist tool for my device, but Stage Manager, Internal Storage, Clock Anamiation UI, doesn't change.

**Comment by 34306** [comment]
Stage Manager on iPhone can be trigger by this shortcut:
https://www.icloud.com/shortcuts/f048f52ca0c14db481d505b1ca8d5085

But it's not working probably. Internal storage should work in your settings. Clock Animation is on lockscreen. Try check that when it changed the time.
