### ISSUE TITLE
Someone should test iOS 18.0.1

### ISSUE THREAD

**Issue by haadifarouk** [straight-tamago/misakaX#303]

**Comment by 75Y** [comment]
works well on me. (test camera shutter and charge limit) iphone 13 mini 18.0.1

**Comment by BlackTeemo** [comment]
Metal Hud frame rate monitoring does not work properly in ipados18.0.1

**Comment by MelvinBraemer** [comment]
@75Y did you just update or recover the file and re-flash it?

**Comment by haadifarouk** [comment]
@BlackTeemo what is that?

**Comment by BlackTeemo** [comment]
Yes, after updating to ipados18.0.1, a new plist file is generated and rewritten by misakaX2.2. The Metal Hud frame rate monitoring switch can be turned on but does not work properly.

**Comment by BlackTeemo** [comment]
> @BlackTeemo what is that?
![image](https://github.com/user-attachments/assets/36e95775-c9df-4273-92ce-2af14506520e)

**Comment by felix2049lou** [comment]
> @75Y did you just update or recover the file and re-flash it?

ask the same question for@75Y

**Comment by Splash04** [comment]
Is battery limit working?

**Comment by Starboy-263** [comment]
It's always on display working?

**Comment by A350-900** [comment]
> works well on me. (test camera shutter and charge limit) iphone 13 mini 18.0.1

Hi! Does dynamic island and charge limit works on 13 mini? Thank you for your help!

**Comment by pippupu** [comment]
13 Pro Max ios 18.0.1 cant work

**Comment by 75Y** [comment]
> Is battery limit working?

yes

**Comment by 75Y** [comment]
> @75Y did you just update or recover the file and re-flash it?

I recover and update to 18.0.1 After update I regenerate plistfile for 18.0.1 and re-flash it

**Comment by pippupu** [comment]
iPad 8 ios 18.0.1 still can work

**Comment by pippupu** [comment]
13 Pro Max open developer mode can work

**Comment by TedKim317** [comment]
What features work and what doesnt

**Comment by 34306** [comment]
should works fine
