### ISSUE TITLE
[MacOS] misakaX.app is damaged and can't be opened

### ISSUE THREAD

**Issue by zulufoxtrot** [straight-tamago/misakaX#310]
Version: 2.2
MacOS version: 14.6.1 (apple silicon)

<img width="372" alt="Screenshot 2024-10-05 at 13 51 11" src="https://github.com/user-attachments/assets/d9f093dd-120c-4b88-8925-fb0cd6c7fb3a">

**Comment by hyxrpk** [comment]
same problem

**Comment by hyxrpk** [comment]
> same problem

fixed, we should first run `xattr -c path/to/misakaX.app`

**Comment by zulufoxtrot** [comment]
This workaround worked, thanks!

**Comment by Dayday552** [comment]
how do i put the command in?

**Comment by Dayday552** [comment]
thats what im wondering

**Comment by AlexTech01** [comment]
> how do i put the command in?

Open your Terminal and type `xattr -c path/to/misakaX.app`. For example, if `misakaX.app` is in your Applications folder, you'd type `xattr -c /Applications/misakaX.app`.

**Comment by Dayday552** [comment]
![IMG_172EC8226115-1](https://github.com/user-attachments/assets/ebf46fc9-5e67-4ad6-9c08-2efd5abafed9)

**Comment by Dayday552** [comment]
![IMG_0691](https://github.com/user-attachments/assets/eaaab436-22b4-4d37-90cd-5538295d1395)

**Comment by Dayday552** [comment]
still confused

**Comment by Dayday552** [comment]
never mind thanks for the support

**Comment by SylvanLiu** [comment]
if official advice "xattr -c /Applications/misakaX.app" does not work for you,
just try following on Terminal:

chmod +x /Applications/misakaX.app/Contents/MacOS/misakaX

sudo xattr -rd com.apple.quarantine /Applications/misakaX.app
