### ISSUE TITLE
ios18.0.1 not working

### ISSUE THREAD

**Issue by SlipxD** [straight-tamago/misakaX#311]
Dynamic island old photo ui not working
plz update

**Comment by Cedi111** [comment]
jes 18.0.1 dont working

**Comment by TedKim317** [comment]
What error seems to appear

**Comment by amaannajam** [comment]
> jes 18.0.1 dont working

Try with updated mobile gestalt file

**Comment by TedKim317** [comment]
What is the error

**Comment by 34306** [comment]
it should be working
