### ISSUE TITLE
iOS 18.0.1 support?

### ISSUE THREAD

**Issue by TedKim317** [straight-tamago/misakaX#317]
Does misaka x work with iOS 18.0.1?

**Comment by haadifarouk** [comment]
> Does misaka x work with iOS 18.0.1?

Yeah

**Comment by TedKim317** [comment]
Does Dynamic Island work

**Comment by haadifarouk** [comment]
> Does Dynamic Island work

Yeah. I'm currently using it.

**Comment by Newhellow-Realring** [comment]
Excuse me, does AOD work with iOS18.0.1?
