### ISSUE TITLE
Does Misaka X support iOS 18.0.1

### ISSUE THREAD

**Issue by TedKim317** [straight-tamago/misakaX#321]

**Comment by Avil-XD** [comment]
Yes working for my 13pro, just do with the updated plist file.

**Comment by TedKim317** [comment]
does dynamic island work

**Comment by HMA28** [comment]
how can i update my plist file?

**Comment by amaannajam** [comment]
> and what is plist file

Mobile gestalt file

**Comment by HMA28** [comment]
where i can fund the updated one?

**Comment by alanu2004** [comment]
will misakax be compatible with ios 18.1 beta 6?

**Comment by amaannajam** [comment]
> where can i find the updated one?

Just run save movile gestalt shortcut then you will get updated once

**Comment by HMA28** [comment]
![image](https://github.com/user-attachments/assets/95ccbfd4-c173-4da0-93f4-c1bf1e6ae31b)

you mean i only press it and it will be updated?

**Comment by HMA28** [comment]
it worked thanks.
