### ISSUE TITLE
iOS 18.1 beta 5 

### ISSUE THREAD

**Issue by Fili010** [straight-tamago/misakaX#326]
Are there any updates for iOS 18.1 beta 5? I can't install Aod on my iPhone 12 Pro

**Comment by Mia090605** [comment]
> Are there any updates for iOS 18.1 beta 5? I can't install Aod on my iPhone 12 Pro 

So far it's only supported up to beta4

**Comment by 34306** [comment]
Not support iOS 18.1b5+
