### ISSUE TITLE
18.1 beta6: Failed to execute script 'restore' due to unhaandled exception

### ISSUE THREAD

**Issue by Yoangloo** [straight-tamago/misakaX#328]
I can also used in beta 5, and it get issue in beta 6.

Here is the log:
pymobiledevice3.exceptions.PyMobileDevice3Exception: Device link error: {'ErrorCode': 205, 'ErrorDescription': 'Domain name cannot contain a slash
(MBErrorDomain/205)', 'MessageName': 'Response'}
[PYI-28808:ERROR] Failed to execute script 'restore' due to unharndled exception!
[Restore] /Applications/misakaX 2.app/Contents/Resources/com.appleMobile Gestalt.plist -> /var/containers/Shared/SystemGroup/
systemgroup.com.apple.mobilegestaltcache/Library/Caches/com.apple.Mobile Gestalt.plist

**Comment by SmallKi-d** [comment]
same issue

**Comment by MelvinBraemer** [comment]
No support for beta 5 and 6 so not an issue..

**Comment by 34306** [comment]
Not support iOS 18.1b5+
