### ISSUE TITLE
Action button does not work

### ISSUE THREAD

**Issue by Janandrew2009** [straight-tamago/misakaX#33]
When I choose the action button and try to use the mute switch to trigger anything it just toggles silent

**Comment by AquaChocomint** [comment]
i think action button requires a physical button.

**Comment by Janandrew2009** [comment]
> i think action button requires a physical button.

If so, why do they have it as an option in Misaka X

**Comment by AquaChocomint** [comment]
> > i think action button requires a physical button.
> 
> If so, why do they have it as an option in Misaka X
idk. i think it was only added as a feature.

**Comment by 34306** [comment]
Hardware issue, it can be fixed if there's a jailbreak for it

**Comment by Janandrew2009** [comment]
Thanks for you'all
