### ISSUE TITLE
Strenge Dynamic Island

### ISSUE THREAD

**Issue by Himadori817** [straight-tamago/misakaX#336]
Hello.
I am using an IPhone 8 and the IOS version is 16.7.10.
I turned on the Dynamic island setting and it works to a point, but the black rectangles are overlapping. I was able to choose between two resolutions on misakaX, so I tried both, but no improvement.
![IMG_3839](https://github.com/user-attachments/assets/78c4c5af-521b-44d5-ab1f-331699ac84b1)

**Comment by 34306** [comment]
Blame apple for this...

**Comment by Himadori817** [comment]
It works completely.
only use “Visibleislands” tweak and change Island’s position (I did set (1,0)).
Thank you.
