### ISSUE TITLE
iPad KeyBoard doesn't Working

### ISSUE THREAD

**Issue by A2215** [straight-tamago/misakaX#35]
Thanks For your Program. I love you.

I'm reporting this because it's a huge problem in real life.

There's a bug where the keyboard doesn't show up on the iPad.

My experience is as follows
-iPad Pro 12.9 5th(M1)
- iPadOS 18.1 Beta3
- Region/language : US/English, Korea/Korean both occurred
- Versions used: 1.4 , 1.5
- Options used: Remove camera sound, AOD, Dynamic Island, charge limit
I've tested all possible options, and when I apply them using Misaka, the keyboard is not always visible.

Thank you for your efforts.

**Comment by ileeric** [comment]
Same problem here... I had to connect my Magic Keyboard to input my password, and fully reset my device to make the keyboard work again

**Comment by mentalfl0w** [comment]
Are you using misakaX to handle two different devices one after the other? I had a keyboard problem once, but I solved it by doing the following: it looks like misakaX doesn't use the newly selected Mobile Gestalt but the first one, so if you're working with two devices successively, try exiting the app completely and selecting the corresponding plist file again.

**Comment by 34306** [comment]
Disable Dynamic Island if you enable it

**Comment by theJayTea** [comment]
Does it fix itself if you just disable Dynamic Island again? I wanna try it out but don't wanna be forced to reset :(
@ileeric @A2215
