### ISSUE TITLE
iPadOS 18.0 TrollStore

### ISSUE THREAD

**Issue by Finnyus** [straight-tamago/misakaX#354]
I tried installing Trollstore on my IPad Air running iPadOS 18.0. MisakaX reports a success, but it doesn't install TrollStore. It just injects the persistance helper from TrollStore into Tips (Now I cant open Tips, obviously). Is TrollStore not supported in iPadOS 18.0, or am I doing something wrong?
![Img](https://github.com/user-attachments/assets/4cc6e469-4090-44bc-b9fa-0dc17d3dd3c0)

**Comment by indicator0** [comment]
TrollStore is not supported on any version beyond 17.0.1. Apple has fixed this, so, maybe never.

**Comment by Finnyus** [comment]
Oh sry… I thought it was compatible since the readme doesn‘t state that it‘s only for iOS 17 and below
