### ISSUE TITLE
Stage Manager On iPad 9th

### ISSUE THREAD

**Issue by Introl-ljl** [straight-tamago/misakaX#356]
If I update my iPad to ios 18.1,will the stage Manager still work?

**Comment by Luca0736** [comment]
No, stage manager will be disabled. At the moment misaka x and nugget do not work on 18.1 global

**Comment by Sprick2007** [comment]
How about Always on display and Dynamic Island (2556) and the Charge limit and also  intelligence, would that work on iOS 18.1 for an iPhone 12?
<img width="1169" alt="MISAKAX" src="https://github.com/user-attachments/assets/79b62704-b561-4047-9cda-4c6c74ebd30c">

**Comment by Luca0736** [comment]
No, until misaka x and nugget are supported on IOS 18.1 (except the beta versions). You can try nugget mobile, which is supported.
