### ISSUE TITLE
Battery Drainage

### ISSUE THREAD

**Issue by Nessunissimo** [straight-tamago/misakaX#36]
Thanks for crating this program first, it's really good, but i had a problem...
after applying the Dynamic Island, AoD, SOS and Boot chime, i've experienced a big change talking about battery drainage. 
My phone last about 1 day, after applying these things, it goes from 80% to 20% in 6/7 hours. i don't know if that's normal.
Thanks in advance for any help ill recive.

-iPhone 13 Pro Max
iOS 18 beta 8

**Comment by EraserCN** [comment]
Same issue

**Comment by hirakujira** [comment]
This is not a bug. Your iPhone doesn't support AOD physically so the screen uses higher frequency than the real AOD.

**Comment by Nessunissimo** [comment]
> This is not a bug. Your iPhone doesn't support AOD physically so the screen uses higher frequency than the real AOD.  

Yes, I believe that this is real... but since it's just a script, I think that with a little bit of coding it is possible to lower the Hz of the screen to 1. They created a chip for this, but even old phones can do it without anything like that, stop lying... with some work it's possible to optimize it. I guess it's just a matter of time.

**Comment by EraserCN** [comment]
> > This is not a bug. Your iPhone doesn't support AOD physically so the screen uses higher frequency than the real AOD.
> 
> Yes, I believe that this is real... but since it's just a script, I think that with a little bit of coding it is possible to lower the Hz of the screen to 1. They created a chip for this, but even old phones can do it without anything like that, stop lying... with some work it's possible to optimize it. I guess it's just a matter of time.

Well, actually 13 Pro Max could lower the Hz to 10, I believe 10Hz can be a great battery saver. But in fact there's still a noticeable battery drain.

**Comment by Nessunissimo** [comment]
> > > This is not a bug. Your iPhone doesn't support AOD physically so the screen uses higher frequency than the real AOD.
> 
> > 
> 
> > Yes, I believe that this is real... but since it's just a script, I think that with a little bit of coding it is possible to lower the Hz of the screen to 1. They created a chip for this, but even old phones can do it without anything like that, stop lying... with some work it's possible to optimize it. I guess it's just a matter of time.
> 
> 
> 
> Well, actually 13 Pro Max could lower the Hz to 10, I believe 10Hz can be a great battery saver. But in fact there's still a noticeable battery drain.

Yes exactly, that's what I was talking about... if they can, it would be great to make the screen go down to 10 hz when AoD is on

**Comment by 34306** [comment]
Hardware issue, which is cannot fix by software :/
