### ISSUE TITLE
Enabling ClockUI doesn't work

### ISSUE THREAD

**Issue by Janneske2001** [straight-tamago/misakaX#4]
Enabling ClockUI results in `<key>SwiftUITimeAnimation</key> <true/>` being added. However, this is not working, the key is not supposed to be added in MobileGestalt. Doing this results in a MobileGestalt that doesn't work at all and every change gets reverted.
![image](https://github.com/user-attachments/assets/77f7be2f-fcf0-4b40-85d7-bdfb717d96b1)
Instead, `<key>SwiftUITimeAnimation</key> <dict> <key>Enabled</key> <true/> </dict>` should be added to `/var/preferences/FeatureFlags/Global.plist`, NOT to MobileGestalt.
![image](https://github.com/user-attachments/assets/48162b0e-813f-4692-b427-f42aee41dd01)

**Comment by 34306** [comment]
Will fix this soon!

**Comment by JustAiden9** [comment]
Has this been fixed with the 1.2 update?
