### ISSUE TITLE
How to turn off Dynamic Island?

### ISSUE THREAD

**Issue by tr-zen1th** [straight-tamago/misakaX#40]
Well, I have tried Dynamic Island on my XR, and it has an error (as you can see on the top of the screen). So i try to turn off Dynamic Island in misakaX.exe, and it doesn’t work (hasn’t tried backup)
When I try to turn off Dynamic Island on iPhone 12, it doesn’t work (and still hasn’t tried backup)

iPhone 12 and iPhone XR
iOS 18 beta 8

Sorry for bad English!

![IMG_3084](https://github.com/user-attachments/assets/60c8f25c-b085-4fc4-9375-039d588374a5)

**Comment by tr-zen1th** [comment]
Update: I have tried restore old backups on iPhone XR, and the error won’t go away 🙂.

**Comment by 34306** [comment]
Please use lastest misakaX 1.6, and press reset MobileGestalt
