### ISSUE TITLE
Time error in AOD and Cannot disable Clock Animation

### ISSUE THREAD

**Issue by xero-xer0** [straight-tamago/misakaX#41]
when the clock animation is enabled, time does not appear correctly in AOD. and it cannot be disabled.
it appears WEIRD if the AOD changes. it shows the letter the middle of changing animation. 
I think you can fix it into disable the animation in AOD.

**Comment by Mowd** [comment]
have the same problem and can't find anywhere to disable animation clock ui

**Comment by 34306** [comment]
Please update misakaX 1.6
