### ISSUE TITLE
Dynamic Island on iPad makes the keyboard disappear

### ISSUE THREAD

**Issue by xero-xer0** [straight-tamago/misakaX#42]
If I enable Dynamic Island on my iPad Pro 12.9" 5th gen M1, the Dynamic Island works wonderful. but my software keyboard almost totally disappear. I can use it only by making it smaller by pinch zoom, movable iPhone-like keyboard. the SW Keyboard UI Totally disappears.

**Comment by mentalfl0w** [comment]
Are you using misakaX to process two different devices one after the other? It looks like misakaX doesn't use the newly selected Mobile Gestalt but the first one, so if you're working with two devices one after the other, try exiting the app completely and selecting the corresponding plist file again.

**Comment by xero-xer0** [comment]
@mentalfl0w Already did it some times. no difference.

**Comment by mentalfl0w** [comment]
> @mentalfl0w Already did it some times. no difference.

Oh...so wired🤔

**Comment by xero-xer0** [comment]
Of course they're wired XD

**Comment by 34306** [comment]
iPad did not in the plan to use with Dynamic Island. Just disable it and all be fine
