### ISSUE TITLE
Apple Intelligence option

### ISSUE THREAD

**Issue by aleTek727** [straight-tamago/misakaX#45]
AoD on iPhone 15 works
Apple Intelligence does not. Is it because in im the EU?

**Comment by iamyx123** [comment]
ONLY iPhone 15pro/pro max is supported.

**Comment by Nessunissimo** [comment]
> ONLY iPhone 15pro/pro max is supported.

than why did they add this functionality?? I mean, if you really want A.I. you can just change your phone and account region... ig it's not fully implemented, that's why it doesn't work. It's just a matter of time. 
Since apple released A.I. officially, this option would be basically useless. Maybe i'm wrong, but i guess they made it to make A.I. work in older phones too.

**Comment by Frank-III** [comment]
You are totally wrong dude. Apple identify in which region you buy an iPhone, regions like China does not have AI support for example.

**Comment by Nessunissimo** [comment]
> You are totally wrong dude. Apple identify in which region you buy an iPhone, regions like China does not have AI support for example.

Actually no, if I buy a phone in Italy and than I move to US I can use the US services. To prove that you're wrong, I'm in Italy with an American apple account, and I have access to Apple News... doesn't Apple identify where you buy your phone? 😂

**Comment by iamyx123** [comment]
> > ONLY iPhone 15pro/pro max is supported.
> 
> than why did they add this functionality?? I mean, if you really want A.I. you can just change your phone and account region... ig it's not fully implemented, that's why it doesn't work. It's just a matter of time. Since apple released A.I. officially, this option would be basically useless. Maybe i'm wrong, but i guess they made it to make A.I. work in older phones too.

I'm wrong. This is the correct answer. AI can be used on devices on iOS18.1.
https://github.com/straight-tamago/misakaX/issues/23#issuecomment-2333690685

**Comment by Frank-III** [comment]
> > You are totally wrong dude. Apple identify in which region you buy an iPhone, regions like China does not have AI support for example.
> 
> Actually no, if I buy a phone in Italy and than I move to US I can use the US services. To prove that you're wrong, I'm in Italy with an American apple account, and I have access to Apple News... doesn't Apple identify where you buy your phone?

still wrong. In some cases yes(as you said Apple News) but for AI no, the way `misakaX` enables AI is to change the Sales area code you could find out from `Settings`->`About`->`Model Number`, it should be end with `LL/A` if you did it correctly.
