### ISSUE TITLE
AoD not turning off when screen is facing a surface or in the pocket

### ISSUE THREAD

**Issue by Nessunissimo** [straight-tamago/misakaX#48]
I noticed that the AoD doesn't turn off when the screen is facing a surface or the pocket, could this happen because I have ClockUi on? 
The AoD doesn't even lower the refresh rate, it would be great if you could add this functionality, just because the battery drain faster.

**Comment by 34306** [comment]
Stock hardware issue because apple does not plan to use that on older devices

**Comment by yuxuant816** [comment]
So do we still have a way to fix it? I'm afraid my phone screen will be damaged as a result. If damaged it will be a huge expense 🤔
