### ISSUE TITLE
Unable to operate on iOS 18.0 beta and no log

### ISSUE THREAD

**Issue by Oscarrain** [straight-tamago/misakaX#49]
<img width="1079" alt="截屏2024-09-07 23 38 55" src="https://github.com/user-attachments/assets/19020a21-9a1b-4d70-aa4f-2548864628d3">

After successfully passing MobileGestalt.plist to this app on Mac, any operation other than rebooting will cause "Unknown error, please check log".
Only such single error shows up several times.
However, there is no log underneath (as the tutorial shows). And even no iphone system info shown on the right top corner. Fullscreening turns out the same.

Rebooting is fine, which shows that connection between Mac and iPhone works.

Please help me find out what I should do to find out where the problem lies?
Thanks a lot.

Environment:
iPhone: iOS 18.0 beta (22A5350a)/ iPhone 15 pm
Mac: MacOS "Sonoma" 14.6.1(23G93)/ M2

**Comment by Mowd** [comment]
Enable dark mode on your Mac then you can see the log.

**Comment by Oscarrain** [comment]
> Enable dark mode on your Mac then you can see the log.

Thanks a lot. Solved.

<img width="1079" alt="截屏2024-09-09 17 50 45" src="https://github.com/user-attachments/assets/5bcfefa7-4571-4f30-8836-cc917dc86b57">
