### ISSUE TITLE
After executing, my device is restoring from iCloud, and I had to turn off Find My, is this normal?

### ISSUE THREAD

**Issue by danielv05** [straight-tamago/misakaX#5]

**Comment by JustAiden9** [comment]
Nope you just wiped your iPhone you should always click continue with partial setup if you get to that screen

**Comment by Tomithan** [comment]
> Nope you just wiped your iPhone you should always click continue with partial setup if you get to that screen

Same for me, i had disbale find me before executing, and i had click with partial setup and my device is restoring from iCloud too.

**Comment by Tomithan** [comment]
> > Nope you just wiped your iPhone you should always click continue with partial setup if you get to that screen
> 
> Same for me, i had disbale find me before executing, and i had click with partial setup and my device is restoring from iCloud too.

Just Clock UI it worked, dynamic island didn't, action button and always on display didn't too
