### ISSUE TITLE
How to turn off Animation Clock UI?

### ISSUE THREAD

**Issue by 123MEMZ** [straight-tamago/misakaX#54]
iPhone 15 Pro
iOS 18.3 Beta 3
misakaX 1.5 Windows Edition

Hello. I can't turn off the "Animation Clock UI" after I turn it on. Is there any way to close it? I've tried "Regenerate MobileGestalt (Reset)" and also tried hitting the "Animation Clock UI" button again but it didn't work. I need your help, thank you very much.

_(Some or all of the above content has been generated by translation. I apologize for any grammatical errors. )_

**Comment by 34306** [comment]
Please update 1.6, it was fixed
