### ISSUE TITLE
License file.

### ISSUE THREAD

**Issue by Crxaw** [straight-tamago/misakaX#60]

**Comment by Crxaw** [comment]
![image](https://github.com/user-attachments/assets/efcf8c6f-d44e-43c1-8696-400079594847)
erm new file would be good if it wasnt taken from nugget / Cowabunga

**Comment by straight-tamago** [comment]
It is provided by lemin. No problem.

**Comment by Crxaw** [comment]
why would you need the license in it?

**Comment by straight-tamago** [comment]
Because misakaX uses his code

**Comment by straight-tamago** [comment]
It is appropriate to include the MIT license file or a link to the license file.
