### ISSUE TITLE
tap to wake isn’t working on iPhone 15

### ISSUE THREAD

**Issue by Latetooth5489** [straight-tamago/misakaX#63]
I use misakaX on my iPhone15(iOS18Beta8) to open Always on Display ,but When the device enters AoD mode, I cannot use tap to wake or swipe up gestures. In order to wake up my device, I can only use raise to wake or press the power button. Is there a solution to this problem? (Or maybe only I have encountered this problem)

**Comment by 34306** [comment]
Tripple tap to wake it

**Comment by Latetooth5489** [comment]
> Tripple tap to wake it

but it still not working ,I mean any operation on AoD is not working :(

**Comment by pelpan** [comment]
Me too （on iPhone 15 plus）
