### ISSUE TITLE
dynamic island issue

### ISSUE THREAD

**Issue by SENTII1337** [straight-tamago/misakaX#70]
how to fix rdar:45025538

**Comment by minh11283** [comment]
hardware problem on Xr and 11 will show rdar error

**Comment by balu790521** [comment]
rdar javítása: iphone 11 ios 18

**Comment by xwvvwz** [comment]
Did you find a solution to this problem?

**Comment by SENTII1337** [comment]
> Did you find a solution to this problem?

no

**Comment by Duy-Thanh** [comment]
Me too...

**Comment by Nightcaat** [comment]
I was able to fix it by selecting the MobileGestalt file I used before enabling Dynamic Island and then clicking Apply.

**Comment by Nightcaat** [comment]
I was able to fix it by selecting the MobileGestalt file I used before enabling Dynamic Island and then clicking Apply

**Comment by SENTII1337** [comment]
> I was able to fix it by selecting the MobileGestalt file I used before enabling Dynamic Island and then clicking Apply

wdym?

**Comment by Nightcaat** [comment]
Click **Select MobileGestalt File**.
![image](https://github.com/user-attachments/assets/a8df8061-92b7-42b3-94e9-c633c8cc2402)
Select the **com.apple.MobileGestalt.plist** file you used before you enabled any features. You should have extracted this file from your device before you started using misakaX.
![image](https://github.com/user-attachments/assets/c2dfa9a4-b60c-4d1d-b193-cb6241779526)
Click **Apply**.
![image](https://github.com/user-attachments/assets/00fa5548-88e5-4940-8c29-dbe25d828c3e)
I was not able to get **Regenerate MobileGestalt (Reset)** to work. This was the only method that fixed broken features for me.

**Comment by Ivy-js** [comment]
and by doing this, its erase features ? or it's keeping feature & erasing the red bar ?

**Comment by Nightcaat** [comment]
It erases features and the red bar. You would have to apply the other features again

**Comment by 34306** [comment]
Changing resolution fix this
