### ISSUE TITLE
iPhone 13 Dynamic Island does not change status bar and keeps the iPhone 13 status bar but with Dynamic Island

### ISSUE THREAD

**Issue by bufferoverflowww** [straight-tamago/misakaX#76]
Hi, I used misakaX to enable Dynamic Island on my iPhone 13 on iOS 18 Dev Beta 8, I chose 2556 Dynamic Island, and Dynamic Island works fine except that the Dynamic Island does not move status bar elements (on iPhone 14 Pro/15/16 the status bar elements move), and when I chose 2796 Dynamic Island the Dynamic Island the same thing happens. This is how the status bar looks like on my iPhone 13 with 2556/2796 Dynamic Island when the Dynamic Island is showing a timer 
![IMG_7414](https://github.com/user-attachments/assets/e06c8349-4b8e-476f-98ec-306efb5d71ce)
and this is how it looks like on an actual iPhone 14 Pro (downloaded from the internet but showing this just as a reference) 
![4C038F17-C5A0-4774-A2E2-C0A4A70A353E](https://github.com/user-attachments/assets/c8d1808b-704e-4765-acef-e7366d74d2ac)
You can see how in the second image some status bar elements move (time, wifi and battery) and some that disappear (only the cellular indicator) but that is not the case on my iPhone 13 (yes I enabled 2556 and 2796 Dynamic Island but still same result) where the status bar elements do not move or disappear at all. Also I don't have the rdar issue where the status bar is red. Waiting for any replies

**Comment by w2wewwww** [comment]
try to change display zoom mode to "larger text"

**Comment by bufferoverflowww** [comment]
> try to change display zoom mode to "larger text"

I did it and it worked except that some apps such as TikTok don't work properly (when editing a vid/slideshow I can't save it to my album because that button is not visible in zoomed mode)
