### ISSUE TITLE
Intel Mac not supported since version 1.6

### ISSUE THREAD

**Issue by dextermo01** [straight-tamago/misakaX#77]
When using "MobileGestalt" tab features, the log says
`zsh:1: bad CPU type in executable: ./dist/misakaX-restore`

When installing TrollStore in "TrollStore" tab, the log says
`zsh:1: bad CPU type in executable: ./dist/misakaX-install_trollstore`

It was working well in version 1.5, and not working in 1.6 and 1.7. 

I would appreciate continued support for Intel-based Macs.

**Comment by straight-tamago** [comment]
i can fix

**Comment by 34306** [comment]
Lastest updated fixed it!
