### ISSUE TITLE
"is damaged and can’t be opened. You should move it to the Trash”

### ISSUE THREAD

**Issue by Julian-Tseu** [straight-tamago/misakaX#81]
1.9 release has is damaged and can’t be opened. You should move it to the Trash” error

**Comment by Julian-Tseu** [comment]
unable to be fixed by xattr -c /path/to/misaka.app

**Comment by Julian-Tseu** [comment]
“sudo xattr -r -d com.apple.quarantine ”is working

**Comment by A2215** [comment]
me too...

**Comment by catwihtfpac** [comment]
i have the same  problem and i still have it. 
for some reason it says "Not enough arguments for option -d. Expected at least 2 but got 1"
I'm on monterey 12

**Comment by arnavdoshi1** [comment]
same issue

**Comment by arnavdoshi1** [comment]
> “sudo xattr -r -d com.apple.quarantine ”is working

expected at least 2 but got 1
