### ISSUE TITLE
Only Dynamic Island work on iOS 18 RC beta

### ISSUE THREAD

**Issue by Nessunissimo** [straight-tamago/misakaX#95]
I tryied to install Dynamic Island, stage manager, action button, charge limit, SOS collision, AoD and iPad app support.
The only feature that work is the Dynamic Island. What happened?

**Comment by mariocmg** [comment]
Same for me

**Comment by mentalfl0w** [comment]
If you use the version 2.0, you need to regenerate a MobileGestalt through shortcut rather than use the old one, because the system is updated, some value in the plist file are changed.(Works for me in my iPad mini6 in iOS 18 RC)

**Comment by Nessunissimo** [comment]
> If you use the version 2.0, you need to regenerate a MobileGestalt through shortcut rather than use the old one, because the system is updated, some value in the plist file are changed.(Works for me in my iPad mini6 in iOS 18 RC)

Yea i know, but actually after applying the features and rebooting, I lose all of them :(

**Comment by mentalfl0w** [comment]
> > If you use the version 2.0, you need to regenerate a MobileGestalt through shortcut rather than use the old one, because the system is updated, some value in the plist file are changed.(Works for me in my iPad mini6 in iOS 18 RC)
> 
> Yea i know, but actually after applying the features and rebooting, I lose all of them :(

Yes, it's a fatal problem, maybe Apple's developers already noticed this bug, so probably from iOS 18 RC, the system will regenerate MobileGestalt every reboot.

**Comment by Techdrips** [comment]
In MisakaX v2.0, which dynamic island did you use, there are fourand i do not know which one to choose. The first doesnt work (top left)
Ios: 18.6-7
Ios: ipad 9/ iphone xs

**Comment by Nessunissimo** [comment]
> In MisakaX v2.0, which dynamic island did you use, there are fourand i do not know which one to choose. The first doesnt work (top left)
> 
> Ios: 18.6-7
> 
> Ios: ipad 9/ iphone xs

To be honest, they're the same. Use standard one, for iPhone 14/15 pro and pro max (2556 and 2796)
